# Dependencies
markdown:            redcarpet
highlighter:         pygments

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               Sean Harger
tagline:             'thoughts on life, tech, and other drugs'
description:         'a blog dedicated towards providing useful and useless information'
url:                 http://wallaceicy06.github.io
baseurl:             http://wallaceicy06.github.io/blog/
paginate:            5

# About/contact
author:
  name:              Sean Harger
  url:               http://seanharger.com
  email:             seanharger93@gmail.com

# Custom vars
version:             1.0.0
